FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    curl \
    git \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql pgsql \
    && docker-php-ext-install pdo pdo_mysql

WORKDIR /var/app/adverts-board

ENTRYPOINT [ "php-fpm" ]