FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    curl \
    git \
    libpq-dev

RUN docker-php-ext-install pdo pdo_pgsql pgsql \
    && docker-php-ext-install pdo pdo_mysql

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

WORKDIR /app

ENTRYPOINT [ "php-fpm" ]