networks:
  adverts-board:
    name: adverts-board

services:
  adverts-nginx:
    container_name: adverts-nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/server/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/app/adverts-board
    networks:
      - adverts-board
    depends_on:
      - adverts-phpfpm
      - adverts-mysql
  adverts-phpfpm:
    container_name: adverts-phpfpm
    build: ./docker/images/php8.1-fpm
    volumes:
      - ./:/var/app/adverts-board
    networks:
      - adverts-board
  adverts-mysql:
    container_name: adverts-mysql
    image: mysql:5.7.16
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/mysql-5.7.16/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=' '
    networks:
      - adverts-board
  adverts-postgres:
    container_name: adverts-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=adverts-board
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    networks:
      - adverts-board